### PR TITLE
[fix/faq_entity] close #35

### LINKED ISSUE #35: [Domain] FAQ엔티티 수정 및 Test Code 작성
# 1. TODO
- [x] Setter 제한
- [x] Constructor에 Builder 설정
- [x] @NoArgsConstructor 에 access를 `AccesLevel.PROTECTED`로 설정

---

# 2. Test Case
- [x] FAQRepository 테스트를 domain/FAQTest 로 변경
- [x] FAQ 변경사항에 맞게 테스트 코드 수정
---

# 3. 유의사항
- 없음

### PR DESCRIPTION
**Pull request by bkRyusim**
1. Fix FAQ Entity
- FAQ

2. Fix Test Code
- rename FAQRepositoryTest to FAQTest
- move FAQTest from `src/test/java/org/rubatophil/www/api/repository` to `src/test/java/org/rubatophil/www/api/domain`

### CODE REVIEW

File: src/test/java/org/rubatophil/www/api/domain/FAQTest.java [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+        FAQ faq = FAQ.builder().question("Q").answer("A").build();
+
+        //when
+        em.persist(faq);
+        Long faqId = faq.getId();
+        FAQ newFaq = em.find(FAQ.class, faqId);
+
+        //then
+        assertEquals(faq.getAnswer(), newFaq.getAnswer());
+        assertEquals(faq.getQuestion(), newFaq.getQuestion());
```
Comment (AllyHyeseongKim) [inline src/test/java/org/rubatophil/www/api/domain/FAQTest.java:39]: DB 안에 저장된 faq를 꺼내서 비교하는게 좋을 것 같아요

**Review by AllyHyeseongKim — CHANGES_REQUESTED** [review]
1 Request Required

**Review by AllyHyeseongKim — APPROVED** [review]
LGTM
